Bau302TodoList/Models/TodoItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Bau302TodoList.Models
{
    public class TodoItem:BaseEntity
    {
        [StringLength(200), Required(ErrorMessage = "Bu alan doldurulmalıdır!"), DisplayName("Başlık")]
        public string Title { get; set; }
        [DisplayName("Açıklama")]
        public string Description { get; set; }
        [DisplayName("Durum")]
        public Status Status { get; set; }
        [DisplayName("Kategori")]
        public int? CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }
        [DisplayName("Dosya Eki")]
        public string Attachment { get; set; }
        [DisplayName("Departman")]
        public int? DepartmentId { get; set; }
        [ForeignKey("DepartmentId")]
        public virtual Department Department { get; set; }
        [DisplayName("Taraf")]
        public int? SideId { get; set; }
        [ForeignKey("SideId")]
        public virtual Side Side { get; set; }
        [DisplayName("Müşteri")]
        public int? CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }
        [DisplayName("Yönetici")]
        public int? ManagerId { get; set; }
        [ForeignKey("ManagerId")]
        public virtual Contact Manager { get; set; }
        [DisplayName("Organizatör")]
        public int? OrganizatorId { get; set; }
        [ForeignKey("OrganizatorId")]
        public virtual Contact Organizator { get; set; }
        [DisplayName("Toplantı Tarihi")]
        [DataType("datetime-local")]
        [Required(ErrorMessage = "Tarih girilmelidir!")]
        public DateTime MeetingDate { get; set; }
        [DisplayName("Planlama Tarihi")]
        [DataType("datetime-local")]
        [Required(ErrorMessage = "Tarih girilmelidir!")]
        public DateTime PlannedDate { get; set; }
        [DisplayName("Bitirme Tarihi")]
        [DataType("datetime-local")]
        [Required(ErrorMessage = "Tarih girilmelidir!")]
        public DateTime FinishDate { get; set; }
        [DisplayName("Revize Tarihi")]
        [DataType("datetime-local")]
        [Required(ErrorMessage = "Tarih girilmelidir!")]
        public DateTime ReviseDate { get; set; }
        [DisplayName("Görüşme Konusu")]
        public string ConversationSubject { get; set; }
        [DisplayName("Destekleyen Firma")]
        public string SupporterCompany { get; set; }
        [DisplayName("Destekleyen Doktor ")]
        public string SupporterDoctor { get; set; }
        [DisplayName("Görüşme Katılımcı Sayısı")]
        [Required(ErrorMessage = "Bu alan boş bırakılamaz!")]
        public int ConversationAttendeeCount { get; set; }
        [DisplayName("Planlanan Organizasyon Tarihi")]
        [DataType("datetime-local")]
        [Required(ErrorMessage = "Tarih girilmelidir!")]
        public DateTime ScheduledOrganizationDate { get; set; }
        [DisplayName("Mailleşme Konusu")]
        public string MaillingSubject { get; set; }
        [DisplayName("Afiş Konusu")]
        public string PosterSubject { get; set; }
        [DisplayName("Afiş Sayısı")]
        public int PosterCount { get; set; }
        [DisplayName("Uzaktan Öğrenme")]
        public string Elearning { get; set; }
        [DisplayName("Tarama Türleri")]
        public string TypesOfScans { get; set; }
        [DisplayName("Taramalardaki Aso Sayısı")]
        public string AsoCountInScans { get; set; }
        [DisplayName("Organizasyon Türleri")]
        public string TypesOfOrganization { get; set; }
        [DisplayName("Organizasyondaki Aso Sayısı")]
        public string AsoCountInOrganization { get; set; }
        [DisplayName("Aşı Ogranizayonu Türleri")]
        public string TypesOfVaccinationOrganization { get; set; }
        [DisplayName("Aşı Ogranizayonundaki Aso Sayısı")]
        public string AsoCountInVaccinationOrganization { get; set; }
        [DisplayName("Afiş İçin Tazminat Miktarı")]
        public string AmountOfCompensationForPoster { get; set; }
        [DisplayName("Kurumsal Verimlilik Raporu")]
        public string CorporateProductivityReport { get; set; }




        
    }
}

Bau302TodoList/Controllers/TodoItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bau302TodoList.Models;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Bau302TodoList.Controllers
{
    [Authorize]
    public class TodoItemsController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: TodoItems
        public async Task<ActionResult> Index()
        {
            var todoItems = db.TodoItems.Include(t => t.Category).Include(t => t.Customer).Include(t => t.Department).Include(t => t.Manager).Include(t => t.Organizator).Include(t => t.Side);
            return View(await todoItems.ToListAsync());
        }

        // GET: TodoItems/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoItem todoItem = await db.TodoItems.FindAsync(id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }
            return View(todoItem);
        }

        // GET: TodoItems/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name");
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name");
            ViewBag.ManagerId = new SelectList(db.Contacts, "Id", "FirstName");
            ViewBag.OrganizatorId = new SelectList(db.Contacts, "Id", "FirstName");
            ViewBag.SideId = new SelectList(db.Sides, "Id", "Name");
            return View();
        }

        // POST: TodoItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,Status,CategoryId,Attachment,DepartmentId,SideId,CustomerId,ManagerId,OrganizatorId,MeetingDate,PlannedDate,FinishDate,ReviseDate,ConversationSubject,SupporterCompany,SupporterDoctor,ConversationAttendeeCount,ScheduledOrganizationDate,MaillingSubject,PosterSubject,PosterCount,Elearning,TypesOfScans,AsoCountInScans,TypesOfOrganization,AsoCountInOrganization,TypesOfVaccinationOrganization,AsoCountInVaccinationOrganization,AmountOfCompensationForPoster,CorporateProductivityReport,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] TodoItem todoItem)
        {
            if (ModelState.IsValid)
            {
                db.TodoItems.Add(todoItem);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", todoItem.CategoryId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", todoItem.CustomerId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name", todoItem.DepartmentId);
            ViewBag.ManagerId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.ManagerId);
            ViewBag.OrganizatorId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.OrganizatorId);
            ViewBag.SideId = new SelectList(db.Sides, "Id", "Name", todoItem.SideId);
            return View(todoItem);
        }

        // GET: TodoItems/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoItem todoItem = await db.TodoItems.FindAsync(id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", todoItem.CategoryId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", todoItem.CustomerId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name", todoItem.DepartmentId);
            ViewBag.ManagerId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.ManagerId);
            ViewBag.OrganizatorId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.OrganizatorId);
            ViewBag.SideId = new SelectList(db.Sides, "Id", "Name", todoItem.SideId);
            return View(todoItem);
        }

        // POST: TodoItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description,Status,CategoryId,Attachment,DepartmentId,SideId,CustomerId,ManagerId,OrganizatorId,MeetingDate,PlannedDate,FinishDate,ReviseDate,ConversationSubject,SupporterCompany,SupporterDoctor,ConversationAttendeeCount,ScheduledOrganizationDate,MaillingSubject,PosterSubject,PosterCount,Elearning,TypesOfScans,AsoCountInScans,TypesOfOrganization,AsoCountInOrganization,TypesOfVaccinationOrganization,AsoCountInVaccinationOrganization,AmountOfCompensationForPoster,CorporateProductivityReport,CreateDate,CreatedBy,UpdateDate,UpdatedBy")] TodoItem todoItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(todoItem).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", todoItem.CategoryId);
            ViewBag.CustomerId = new SelectList(db.Customers, "Id", "Name", todoItem.CustomerId);
            ViewBag.DepartmentId = new SelectList(db.Departments, "Id", "Name", todoItem.DepartmentId);
            ViewBag.ManagerId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.ManagerId);
            ViewBag.OrganizatorId = new SelectList(db.Contacts, "Id", "FirstName", todoItem.OrganizatorId);
            ViewBag.SideId = new SelectList(db.Sides, "Id", "Name", todoItem.SideId);
            return View(todoItem);
        }

        // GET: TodoItems/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoItem todoItem = await db.TodoItems.FindAsync(id);
            if (todoItem == null)
            {
                return HttpNotFound();
            }
            return View(todoItem);
        }

        // POST: TodoItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            TodoItem todoItem = await db.TodoItems.FindAsync(id);
            db.TodoItems.Remove(todoItem);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public void ExportToExcel()
        {
            var grid = new GridView();
            grid.DataSource = from todoitems in db.TodoItems.ToList()
                              select new
                              {
                                  Baslik = todoitems.Title,
                                  Aciklama = todoitems.Description,
                                  Kategori = todoitems.Category.Name,
                                  DosyaEki = todoitems.Attachment,
                                  Departman = todoitems.Department.Name,
                                  Taraf = todoitems.Side.Name,
                                  Müsteri = todoitems.Customer.Name,
                                  Yonetici = todoitems.Manager.FirstName,
                                  Organizator = todoitems.Organizator.FirstName,
                                  Durum = todoitems.Status,
                                  ToplantiTarihi = todoitems.MeetingDate,
                                  PlanlananTarih = todoitems.PlannedDate,
                                  BitirilmeTarihi = todoitems.FinishDate,
                                  RevizeTarihi = todoitems.ReviseDate,
                                  GorusmeKonusu = todoitems.ConversationSubject,
                                  DestekleyenFirma = todoitems.SupporterCompany,
                                  DestekleyenHekim = todoitems.SupporterDoctor,
                                  GorusmeKatilimciSayisi = todoitems.ConversationAttendeeCount,
                                  PlanlananOrganizasyonTarihi = todoitems.ScheduledOrganizationDate,
                                  MailKonuları = todoitems.MaillingSubject,
                                  AfisKonusu = todoitems.PosterSubject,
                                  AfisSayisi = todoitems.PosterCount,
                                  Elearning = todoitems.Elearning,
                                  YapilanTaramalarınTurleri = todoitems.TypesOfScans,
                                  YapilanTaramalardakiAsoSayisi = todoitems.AsoCountInScans,
                                  OrganizasyonTurleri = todoitems.TypesOfOrganization,
                                  OrganizasyondakiAsoSayisi = todoitems.AsoCountInOrganization,
                                  AsıOrganizasyonTurleri = todoitems.TypesOfVaccinationOrganization,
                                  AsıOrganizasyonundakiAsoSayisi = todoitems.AsoCountInVaccinationOrganization,
                                  AfisicinTazminatMiktari = todoitems.AmountOfCompensationForPoster,
                                  KurumsalVerimlilikRaporu = todoitems.CorporateProductivityReport,

Bau302TodoList/Views/TodoItems/Index.cshtml
@model IEnumerable<Bau302TodoList.Models.TodoItem>

@{
    ViewBag.Title = "Yapılacaklar Listesi";
}

<h2>Yapılacaklar Listesi</h2>

<p>
    @Html.ActionLink("Yeni Kayıt", "Create", null, new { @class = "btn red btn-outline" })
    <a class="dt-button buttons-excel buttons-html5 btn yellow btn-outline" tabindex="0" aria-controls="sample_1" href="@Url.Action("ExportToExcel", "TodoItems")" style="float:right;"> <span>Excele Aktar</span> </a>

    <a class="dt-button buttons-excel buttons-html5 btn purple btn-outline" tabindex="0" aria-controls="sample_1" href="@Url.Action("ExportToCsv", "TodoItems")" style="float:right;"> <span>CSV Aktar</span> </a>
</p>
<table class="table table-striped tab-hover" id="tblRecords">
    <thead>
        <tr>
            <th class="text-nowrap all">
                @Html.DisplayNameFor(model => model.Category.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Department.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Manager.FirstName)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Organizator.FirstName)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Side.Name)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Attachment)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.MeetingDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.PlannedDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.FinishDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.ReviseDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.ConversationSubject)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.SupporterCompany)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.SupporterDoctor)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.ConversationAttendeeCount)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.ScheduledOrganizationDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.MaillingSubject)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.PosterSubject)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.PosterCount)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.Elearning)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.TypesOfScans)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.AsoCountInScans)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.TypesOfOrganization)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.AsoCountInOrganization)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.TypesOfVaccinationOrganization)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.AsoCountInVaccinationOrganization)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.AmountOfCompensationForPoster)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.CorporateProductivityReport)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.UpdateDate)
            </th>
            <th class="text-nowrap">
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </th>
            <th data-orderable="false" class="all">Eylemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Manager.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Organizator.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Side.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Attachment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetingDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlannedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FinishDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReviseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConversationSubject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SupporterCompany)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SupporterDoctor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConversationAttendeeCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScheduledOrganizationDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaillingSubject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PosterSubject)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PosterCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Elearning)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypesOfScans)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AsoCountInScans)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypesOfOrganization)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AsoCountInOrganization)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TypesOfVaccinationOrganization)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AsoCountInVaccinationOrganization)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AmountOfCompensationForPoster)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CorporateProductivityReport)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedBy)
                </td>
                <td>
                    @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Ayrıntılar", "Details", new { id = item.Id }, new { @class = "btn btn-success" })
                    @Html.ActionLink("Sil", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>